import * as z from 'zod'

export const systemDataSchema = z.object({
  platform_name: z.string().optional(),
  slogan: z.string().optional(),
  login_bg_image_url: z.string().optional(),
  login_title: z.string().optional(),
  login_subtitle: z.string().optional(),
  login_impact_text: z.string().optional(),
  logo_url: z.string().optional(),
  browser_icon_url: z.string().optional(),
  menu_logo_size: z.coerce.number().optional(),
  active_theme: z.string().optional(),
  razao_social: z.string().optional(),
  cnpj: z.string().optional(),
  show_cnpj: z.boolean().optional(),
  email: z.string().optional(),
  phone: z.string().optional(),
  mobile: z.string().optional(),
  address_street: z.string().optional(),
  address_number: z.string().optional(),
  address_complement: z.string().optional(),
  address_city: z.string().optional(),
  address_state: z.string().optional(),
  address_zip: z.string().optional(),
  responsible_name: z.string().optional(),
  responsible_cpf: z.string().optional(),
  responsible_role: z.string().optional(),
  responsible_email: z.string().optional(),
  responsible_phone: z.string().optional(),
  business_hours: z.string().optional(),
  scheduling_interval_minutes: z.coerce.number().optional(),
  quote_validity_days: z.coerce.number().optional(),
  records_per_page: z.coerce.number().optional(),
  session_lifetime: z.coerce.number().optional(),
  dark_mode: z.boolean().optional(),
  language: z.string().optional(),
  libras_enabled: z.boolean().optional(),
  footer_icon_size: z.coerce.number().optional(),
  terms_uso: z.string().optional(),
  terms_lgpd: z.string().optional(),
  terms_cookies: z.string().optional(),
  stripe_public_key: z.string().optional(),
  stripe_secret_key: z.string().optional(),
  stripe_webhook_secret: z.string().optional(),
  stripe_pix_enabled: z.boolean().optional(),
  stripe_pass_fees_to_customer: z.boolean().optional(),
  stripe_card_fee_percentage: z.coerce.number().optional(),
  stripe_card_fee_fixed: z.coerce.number().optional(),
  asaas_production_key: z.string().optional(),
  asaas_sandbox_key: z.string().optional(),
  asaas_webhook_secret: z.string().optional(),
  asaas_payment_environment: z.string().optional(),
})

export type SystemDataFormValues = z.infer<typeof systemDataSchema>
